{{- if hasKey .Values.extraArgs "expander" }}
{{- if and (.Values.expanderPriorities) (contains "priority" .Values.extraArgs.expander) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
  labels:
{{ include "cluster-autoscaler.labels" . | indent 4 }}
  {{- if .Values.priorityConfigMapAnnotations }}
  annotations:
{{ toYaml .Values.priorityConfigMapAnnotations | indent 4 }}
  {{- end }}
data:
  priorities: |-
{{ .Values.expanderPriorities | indent 4 }}
{{- end -}}
{{- end -}}
