{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
{{ include "cluster-autoscaler.labels" . | indent 4 }}
  name: {{ template "cluster-autoscaler.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
{{- if contains "priority" (default "" .Values.extraArgs.expander) }}
      - list
      - watch
{{- end }}
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - cluster-autoscaler-status
{{- if contains "priority" (default "" .Values.extraArgs.expander) }}
      - cluster-autoscaler-priority-expander
{{- end }}
    verbs:
      - delete
      - get
      - update
{{- if contains "priority" (default "" .Values.extraArgs.expander) }}
      - watch
{{- end }}
{{- if  eq (default "" (index .Values.extraArgs "leader-elect-resource-lock")) "configmaps" }}
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - cluster-autoscaler
    verbs:
      - get
      - update
{{- end }}
{{- end -}}
